name: Notificación push a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Notificación push devops itla
        run: |
          curl -H "Title: ITLA's devops Team - Alert" \
               -H "Priority: default" \
               -d "El Usuario ${{ github.actor }} realizó push al repositorio ${{ github.repository }} con el siguiente:" \
               -d "Mensaje: ${{ github.event.head_commit.message }}" \
               https://ntfy.sh/Practica-4-CI
