name: Notificación push a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Notificación push devops itla
        env:
          MSG: |
            El Usuario ${{ github.actor }} realizó push al repositorio ${{ github.repository }} del branch ${{ github.ref_name }}
            Mensaje del commit: ${{ github.event.head_commit.message }}
            Link: ${{ github.event.head_commit.url }}
        run: |
          curl -H "Title: ITLA's devops Team - Alert" \
               -H "Priority: default" \
               -d "$MSG" \
               https://ntfy.sh/Practica-4-CI
